# Generated by Django 5.2.6 on 2025-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='papers/')),
                ('title', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=100)),
                ('exam_semester', models.CharField(max_length=50)),
                ('exam_year', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
